import {
  TypeIcon as type,
  type LucideIcon,
  Moon,
  SunMedium,
  Laptop,
  Plus,
  Book,
  Users,
  DollarSign,
  Calendar,
  Menu,
  MoreHorizontal,
  ArrowUpRight,
  CreditCard,
  Activity,
  User,
  Piano,
  Drum,
  Guitar,
  PianoIcon as Violin,
  Music,
  Wallet,
  TrendingUp,
  ArrowDownRight,
  CheckCircle,
  XCircle,
} from "lucide-react"

export type Icon = LucideIcon

export const Icons = {
  sun: SunMedium,
  moon: Moon,
  laptop: Laptop,
  plus: Plus,
  book: Book,
  users: Users,
  dollarSign: DollarSign,
  calendar: Calendar,
  menu: Menu,
  moreHorizontal: MoreHorizontal,
  arrowUpRight: ArrowUpRight,
  creditCard: CreditCard,
  activity: Activity,
  user: User,
  piano: Piano,
  drum: Drum,
  guitar: Guitar,
  violin: Violin,
  music: Music,
  wallet: Wallet,
  trendingUp: TrendingUp,
  arrowDownRight: ArrowDownRight,
  checkCircle: CheckCircle,
  xCircle: XCircle,
  type: type,
}
