# Bun Configuration for P-Core
# Optimizes Bun performance for Next.js development

[install]
# Package installation settings
auto = "auto"
production = false
optional = true
exact = false
peer = true
registry = "https://registry.npmjs.org/"

[install.lockfile]
# Lockfile configuration
save = true
print = "yarn"

[run]
# Script execution settings
bun = false

[transpiler]
# Transpiler settings
allowBunRuntime = true

[test]
# Test runner settings
root = "./"
preload = []
